---
kind: pipeline
type: docker
name: default
steps:
  - name: run gitleaks
    image: plugins/gitleaks
    settings:
      path: .

  - name: hadolint
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint  Dockerfile

  - name: shellcheck
    image: koalaman/shellcheck-alpine:stable
    commands:
      - "shellcheck filter.sh"

  - name: docker_build_and_push_master
    image: plugins/docker
    settings:
      username: quotengrote
      password:
        from_secret: DOCKERHUB_PASS
      dockerfile: Dockerfile
      repo: quotengrote/miniflux-filter
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: docker_build_and_push
    image: plugins/docker
    settings:
      username: quotengrote
      password:
        from_secret: DOCKERHUB_PASS
      dockerfile: Dockerfile
      repo: quotengrote/miniflux-filter
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_COMMIT_BRANCH}
    when:
      event:
        exclude:
          - pull_request
