---
kind: pipeline
type: docker
name: default
steps:
  - name: run gitleaks
    image: plugins/gitleaks
    settings:
      path: .

  - name: hadolint
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint  Dockerfile

  - name: shellcheck
    image: koalaman/shellcheck-alpine:stable
    commands:
      - "shellcheck filter.sh"

  - name: docker_build_and_push_selfhosted
    image: plugins/docker
    settings:
      username:
        from_secret: OCI-REGISTRY-USER
      password:
        from_secret: OCI-REGISTRY-PASS
      dockerfile: Dockerfile
      repo: registry.mgrote.net/miniflux-filter
      registry: registry.mgrote.net
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_COMMIT_BRANCH}
        - latest
    when:
      event:
        exclude:
          - pull_request

  - name: docker_build_and_push_dockerhub
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      dockerfile: Dockerfile
      repo: quotengrote/miniflux-filter
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_COMMIT_BRANCH}
        - latest
    when:
      event:
        exclude:
          - pull_request
