---
kind: pipeline
type: docker
name: linting

steps:
  - name: gitleaks
    image: plugins/gitleaks
    settings:
      path: .
    when:
      event:
        exclude:
          - tag

  - name: hadolint
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint Dockerfile

  - name: shellcheck
    image: koalaman/shellcheck-alpine:stable
    commands:
      - "shellcheck filter.sh"

---
kind: pipeline
type: docker
name: selfhosted
depends_on: # bezieht sich auf linting pipeline
  - linting
steps:
  - name: docker_build_and_push_selfhosted
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: registry.mgrote.net/miniflux-filter
      registry: registry.mgrote.net
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_COMMIT_BRANCH}
        - latest
    when:
      event:
        exclude:
          - pull_request
          - tag

  - name: docker_build_and_push_selfhosted_tag
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: registry.mgrote.net/miniflux-filter
      registry: registry.mgrote.net
      tags:
        - ${DRONE_TAG}
    when:
      event:
        - tag
