version: '3.2'
services:
  mf-filter:
    container_name: mf-filter
    restart: always
    environment:
      - TZ=Europe/Berlin
      - MF_AUTH_TOKEN=XN2klsvvD[...]-dcHPaeQ=
      - MF_API_URL=https://miniflux.[...].net/v1
      - MF_SLEEP=60
      #- MF_DEBUG=1
    image: quotengrote/miniflux-filter:latest
    volumes:
      - ./filter.txt:/data/filter.txt
