version: '3.2'
services:
  mf-filter:
    container_name: mf-filter
    restart: always
    environment:
      - TZ=Europe/Berlin
      - MF_AUTH_TOKEN=XN2klsvvD[...]-dcHPaeQ=
      - MF_API_URL=https://miniflux.[...].net/v1
      - MF_SLEEP=60
      #- MF_DEBUG=1
    image: quotengrote/miniflux-filter:latest@sha256:a99744babfb63fa4566db0ed0219fbffe7580d5dae20b2b018a3bdc8d05aa0c5
    volumes:
      - ./filter.txt:/data/filter.txt
