---
depends_on:
  - lint

variables: # https://woodpecker-ci.org/docs/usage/advanced-usage
  - &VERSION 'v1.0.${CI_PIPELINE_NUMBER}' # wird für die Docker-Tags verwendet

steps:
  selfhosted_push:
    image: "woodpeckerci/plugin-docker-buildx:3.0.1@sha256:c7ac0b01243466bef93863591940ce5eacf59759e9045433a6fc28d20c696d01"
    settings:
      dockerfile: Dockerfile
      repo: registry.mgrote.net/miniflux-filter
      registry: registry.mgrote.net
      tags:
        - *VERSION
        - ${CI_COMMIT_SHA:0:8}
        - ${CI_COMMIT_BRANCH}
        - latest
    when:
      - evaluate: 'CI_COMMIT_AUTHOR_EMAIL != "renovate@mgrote.net"'
    ...
