---
steps:
  gitleaks:
    image: zricethezav/gitleaks:v8.18.0
    commands:
      - gitleaks detect --no-git --verbose --source $CI_WORKSPACE
    when:
      event:
        exclude:
          - tag
  hadolint:
    image: hadolint/hadolint:latest-debian@sha256:9cef74a390694cdc01dd119cbba9adac5bb6671ce67d8d79eb7ec68f497a3684
    commands:
      - hadolint Dockerfile
    when:
      event:
        exclude:
          - tag
