---
steps:
  gitleaks:
    image: zricethezav/gitleaks:v8.18.1@sha256:6945c62ca019ead32bc337ab0c9fd055e98d82961765d38b7ccccc84dae95d0f
    commands:
      - gitleaks detect --no-git --verbose --source $CI_WORKSPACE
    when:
      event:
        exclude:
          - tag
  hadolint:
    image: pipelinecomponents/hadolint:0.25.9@sha256:9cef74a390694cdc01dd119cbba9adac5bb6671ce67d8d79eb7ec68f497a3684
    commands:
      - hadolint Dockerfile
    when:
      event:
        exclude:
          - tag
